package commands.enums;

public enum CommandType {
    CREATEMEMBER,
    SHOWALLPEOPLE,
    SHOWPERSONSACTIVITY,
    CREATENEWTEAM,
    SHOWALLTEAMS,
    ADDPERSONTOTEAM,
    SHOWALLTEAMMEMBERS,
    CREATEANEWBOARD,
    SHOWALLBOARDS,
    SHOWBOARDACTIVITY,

    CREATEBUG,
    CREATESTORY,
    CREATEFEEDBACK,

    CHANGEPRIORITY,

    CHANGEBUGSEVERITY,

    CHANGESTATUS,

    CHANGESTORYSIZE,

    CHANGEFEEDBACKRATING,

    ASSIGNWORKITEM,
    UNASSIGNWORKITEM,

    ADDCOMMENTTOWORKITEM,

    LISTALL,
    FILTERBUGS,
    FILTERSTORIES,
    FILTERFEEDBACK,

    FILTERBYSTATUS,
    FILTERBYASSIGNEE,
    FILTERBYSTATUSANDASSUGNEE,

    SORTBYTITLE,
    SORTBYPRIORITY,
    SORTBYSEVERITY,
    SORTBYSIZE,
    SORTBYRATING

}
